name: Pintos CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Clear any old GHCR credentials
      - name: Clear old GHCR login
        run: docker logout ghcr.io || true

      # Log in to your personal GHCR using PAT
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: itsbushie
          password: ${{ secrets.GHCR_PAT }}

      # Set up pintos directory
      - name: Set up directory on runner
        run: |
          mkdir pintos
          mv src pintos/
          mv setup.sh pintos/
          mv README.md pintos/

      # Pull the prebuilt image from your GHCR and run
      - name: Compile and Run Pintos
        run: |
          docker run --pull=missing \
            --rm \
            -e BXSHARE='/home/BUOS/toolchain/x86_64/share/bochs' \
            --mount type=bind,source="$(pwd)/pintos",target=/home/BUOS/pintos \
            ghcr.io/itsbushie/pintos:latest \
            /bin/bash -c " \
              cd /home/BUOS/pintos && \
              source setup.sh && \
              cd src/threads && \
              make clean && \
              make \
            "
